### ISSUE TITLE
guess what?  Table not rendering...

### ISSUE THREAD

**Issue by spamalope01** [codefellows/seattle-201n3#29]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
N10

2. What is the unexpected outcome of your code?
I have the table hours row showing but none of the rest of the table is generating.  i *think* i know where it's screwing up, but i'm not sure.  I'm getting a 'renderStore is not a function' error in the console.

I have it added to my object constructor but that may not be the right place for it:
```function Store (storeName, minCust, maxCust, avgCookie, id) {
  this.storeName = storeName;
  this.minCust = minCust;
  this.maxCust = maxCust;
  this.avgCookie = avgCookie;
  this.totals = [];
  this.grandTotal = 0;
  stores.push(this); //pushes new stores (instances, when we use NEW STORE) into the stores array
  this.renderStore = renderStore(tableView, this);
};```
 

3. What is the expected outcome of your code?
the table rows will generate with each store and hourly data.  i'm not to the capturing info form the input form yet.

**Comment by sjschmidt44** [comment]
``` javascript
function Store (storeName, minCust, maxCust, avgCookie, id) {
  this.storeName = storeName;
  this.minCust = minCust;
  this.maxCust = maxCust; 
  this.avgCookie = avgCookie;
  this.totals = [];
  this.grandTotal = 0;
  stores.push(this); //pushes new stores (instances, when we use NEW STORE) into the stores array
  this.renderStore = renderStore(tableView, this); 
};
```
Your issue is on the final line where you're trying to assign a new property of each instance as `this.renderStore`. Look at the line above it and note that we're not assignment anything to properties, which means that we can make this constructor `do` things other than just assign properties to each instance. 

I believe you have `renderStore` defined as a method of the `Store` object, not on the prototype. If that's so, then you simply need to call the method and give it your arguments; no need to assign it to a property.

**Comment by sjschmidt44** [comment]
You're doing fine! Keep working on debugging!
