### ISSUE TITLE
assignment 11

### ISSUE THREAD

**Issue by sbachtel** [codefellows/seattle-201n3#35]
## When submitting a request for lab help, please include the following information:

1. What assignment are you working on?
I am working on the stretch part of assignment 11, I can't quite wrap my head around the example you showed us in class last night. I have been looking online for help, but all I seem to find is jQuery examples.  

Do you have any suggestions on where I can look online for some clarity to my problem? I have been searching under dynamic html (not sure this is the correct thing to be searching for). 

Thanks,

Steve

**Comment by sjschmidt44** [comment]
Hey Steven, Check in with me tonight as well for more clarity, but the stretch goal for N11 (which is an unpublished assignment, meaning you don't have to turn it in) is to really dial in your CSS so that you can use this as a showcase project when you start pushing your online portfolio. 

If you want more info please let me know!
